### ISSUE TITLE
[BUG] Echo args dead on NeoVim >= 0.5 ? 

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#146]
**Describe the bug**
Since NeoVim 0.5 became stable I have not been able to get scnvim's echo args functionality to work properly. It may very well be down to me making a silly mistake, but anyway here goes.

**Options**:
`vim.g.scnvim_echo_args` is set to 1

**Symptoms**
Manually calling `SCNvim.methodArgs("Window.new")` works fine. It prints the correct info in vim. But triggering via calling `:call scnvim#util#echo_args()` does nothing. 

Poking around in `scnvim#util#echo_args()` it seems (checked by adding simple echom statements) this main conditional is not triggered: https://github.com/davidgranstrom/scnvim/blob/e2c1e2f1f9f2480ba88a8832a35b3aba65bb9ed9/autoload/scnvim/util.vim#L42-L55

I added a simple print statement to the SCNvim.methodArgs method to see when/if it was even triggered and it does not seem the vimscript function triggers it at all but manually calling the function from SuperCollider does

**Expected behavior**
That scnvim#util#echo_args() prints the arguments as before

**Steps to reproduce**

**Additional context**

**Information**
- `nvim --version`: I tried both 0.5 and a version built from latest github source
- Operating system: Arch Linux
- Running scnvim in a Terminal/GUI: Terminal

**Comment by madskjeldgaard** [comment]
For now I have fixed this for myself by using the following lua function:
```lua

function echo_sc_args()
	local lookup = vim.fn.expand("<cexpr>")
	require'scnvim'.send_silent("SCNvim.methodArgs(\"" .. lookup .. "\")")
end

```
If you have your mapping call this function, it will work fine (at least it does for me)

**Comment by salkin-mada** [comment]
I have also been experimenting with line parsing using __get_current_line()_ and _cWORD_. 
Goal is to leave the ScObject vim function behind and go for full lua parsing. 
Still not completely there. **But works**. No trig echo bug.

![scrn-2021-07-29_13-08-15](https://user-images.githubusercontent.com/12082586/127483008-847f2815-c816-4276-9591-637c361bbe28.png)

So another work around is to use [this](https://github.com/salkin-mada/scnvim/tree/salkin-dev)  dev branch (up to date with upstream/master) operating with "floating window args" and automatic yanking to any " register.

* config
```lua
        use {
            'salkin-mada/scnvim',
            branch = 'salkin-dev',
            run = ":call scnvim#install()",
            config = function ()
                vim.g.scnvim_snippet_format = "snippets.nvim"
                vim.g.scnvim_floating_args_max_width = 60
                -- vim.g.scnvim_floating_args_show_full = true
                -- vim.g.scnvim_floating_args_linebreak = false
                vim.g.scnvim_floating_args_register = "s"
            end
        }

```
* mapping example
```lua
        {'n', ';', ':call scnvim#util#args_popup_toggle()<cr>'}
```

**Comment by davidgranstrom** [comment]
@madskjeldgaard Thanks for the report! Are you (and @salkin-mada) using the supercollider treesitter parser for syntax highlighting? I think we need to rewrite the function to work with treesitter nodes instead, since I don't think the standard syntax files are sourced if a treesitter parser exists for the buffer?

That particular function is long due for a refactor anyways, it was something I wrote very early in the scnvim development and was never quite happy with. A lua version would be much nicer :)

**Comment by salkin-mada** [comment]
Yepp. We are using treesitter.
A lua effort would be fantastic.

**Comment by davidgranstrom** [comment]
I will give this a try in #145 since it aims to improve and re-implement the "echo args" feature (along with more intelligent completion)

**Comment by davidgranstrom** [comment]
I think this should be fixed now by #150 that was just merged. Let me know otherwise and we can reopen this issue.
