### ISSUE TITLE
[BUG] Unknown function: __scnvim_server_start

### ISSUE THREAD

**Issue by aleksandryakunichev** [davidgranstrom/scnvim#32]
**Describe the bug**
Opening any file with extension `.scd` provides an error in Neovim.

```
Error detected while processing /Users/<USERNAME>/.config/nvim/plugged/scnvim/ftplugin/supercollider/supercollider.vim:
line   34:
E117: Unknown function: __scnvim_server_start
E15: Invalid expression: __scnvim_server_start(port)
```

**Steps to reproduce**
Open any file with `.scd` extension.

**Additional context**
Simply installed `scnvim` and  `ultisnips` via `Plug`.

**Information**
- `nvim --version`: `NVIM v0.3.7`
- Operating system: `macOS Mojave 10.14.5 (18F132)`
- `python3 --version`: `Python 3.7.3`

**Comment by aleksandryakunichev** [comment]
Weirdly, but calling `SCNvimStart` — starts the server and code execution works fine, but when I'm trying to generate assets via `SCNvimTags` — SuperCollider crashes.

**Comment by davidgranstrom** [comment]
@aleksandryakunichev Thanks for the report! Could you run `:UpdateRemotePlugins` and then restart nvim to see if that resolves your issue?

I will look into your other report as well about `SCNvimTags`.

**Comment by aleksandryakunichev** [comment]
@davidgranstrom Thanks for advice. After running `:UpdateRemotePlugins` I've received the message:

```
remote/host: python3 host registered plugins ['deoplete']
remote/host: generated rplugin manifest: /Users/<USERNAME>/.local/share/nvim/rplugin.vim
```

But the error does not go away :(

Here is my [nvim config](https://github.com/aleksandryakunichev/.vimrc/blob/master/init.vim#L113) if it can help!

**Comment by davidgranstrom** [comment]
@aleksandryakunichev Okay, `scnvim` should also be registered as a remote plugin in the output that you posted. Could it be that you are still running the older python client for neovim? `scnvim` was developed after they renamed the package to `pynvim` (the older one was called `neovim`), here is a link on how to update to the latest release: https://github.com/neovim/neovim/wiki/Following-HEAD#20181118

 In case you are already running `pynvim` and updating doesn't resolve your issue, could you please post the output from the `scnvim` section after running: `:checkhealth`?

**Comment by aleksandryakunichev** [comment]
@davidgranstrom Thanks for help! It was the case of error, yes. Removing `neovim` package and reinstalling `pynvim` fixes the error.

But tags generation still crashes SuperCollider :(

`:checkhealth` shows everything is OK:

```
 18 ## scnvim
 19   - OK: has("timers") - success
 20   - INFO: using g:scnvim_sclang_executable = /Applications/SuperCollider.app/Contents/MacOS/sclang
 21   - INFO: sclang executable: /Applications/SuperCollider.app/Contents/MacOS/sclang
 22   - INFO: has("python3") - success
```

And SuperCollider crash error:
```
Process:               sclang [20992]
Path:                  /Applications/SuperCollider.app/Contents/MacOS/sclang
Identifier:            net.sourceforge.supercollider
Version:               3.10.2 (3.10.2)
Code Type:             X86-64 (Native)
Parent Process:        nvim [16953]
Responsible:           sclang [20992]
User ID:               501

Date/Time:             2019-06-21 15:58:05.910 +0300
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        42D7E363-6F70-6CF8-86E3-96E66413B8EB


Time Awake Since Boot: 9300 seconds

System Integrity Protection: enabled

Crashed Thread:        22

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000010d567000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [20992]
```

**Comment by davidgranstrom** [comment]
@aleksandryakunichev Good to hear that it worked!

Regarding the tags generation, I have heard reports about this and have also been able to reproduce it locally at some point, but not anymore unfortunately. 

I have pushed a possible work-around. If you'd like you could checkout the fix by changing branch in your nvim config :

```
Plug 'davidgranstrom/scnvim', {'for': 'supercollider', 'branch': 'topic/fix-tags-gen'}
```
and then do `:PlugUpdate`. 

If you try it out and it works, please let me know so I can merge it! :)

**Comment by aleksandryakunichev** [comment]
@davidgranstrom Nope, still the same.

But, I've found a way to generate tags though :)

When I'm starting SuperCollider with `:SCNvimStart` and after it is booted tun `:SCNvimTags`, then it crashes. But! If I boot the server via `s.boot` and *then* run `:SCNvimTags` then everything is going fine: tags are generated and working with `deoplete`. Maybe I've missed this information in the `README`, excuse me if so.

Thanks a lot for your help! 💙

**Comment by davidgranstrom** [comment]
@aleksandryakunichev Okay, thanks for trying it out! I'm glad you found a work-around. I will keep the topic branch around for a while and see if I can sort this thing out.. need to do some more debugging on the sclang side.
