### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cdbzb** [davidgranstrom/scnvim#68]
**Problem on launching nvim after running PlugUpdate**

I now receive the following error on launch:

[scnvim] Vim(call):E5108: Error while calling lua chunk for luaeval(): /Users/michael/.config/nvim/plugged/scnvim/lua/udp.lua:12: attempt to index upva
lue 'uv' (a nil value)

afterward trying to display ScDoc file via 'K' shortcut I get in the post window:

CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of NetAddr>
	Meta_SCNvim:sendJSON
		arg this = <instance of Meta_SCNvim>
		arg object = "{"action":{"help":{"uri":"/U..."
		arg vimPort = ""
	Meta_SCNvim:openHelpFor
		arg this = <instance of Meta_SCNvim>
		arg text = "Song"
		arg vimPort = ""
		arg pattern = "/usr/local/bin/pandoc"
		arg pandocPath = nil
		var msg = "{"action":{"help":{"uri":"/U..."
		var uri = <instance of URI>
		var path = "/Users/michael/Library/Appli..."
		var outputPath = "/Users/michael/Library/Appli..."
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_NetAddr_SendRaw' failed.
Wrong type.
RECEIVER: a NetAddr(127.0.0.1, )

status line fails to display

**Information**
- `nvim --version`: 0.3.5
- Operating system: Mac
- Running scnvim in a Terminal/GUI: iTerm2

**Comment by davidgranstrom** [comment]
The minimum required version of nvim has increased to 0.4.3, the error should be resolved once you’ve updated.

**Comment by cdbzb** [comment]
Thanks for your speedy reply.

After updraging NeoVim I still get the following in the post window when I try to view the help system (and no status line!)

/bin/sh: nil: command not found
error: primitive '_netaddr_sendraw' failed.
wrong type.
receiver:
instance of netaddr {    (0x10b7abb18, gc=6c, fmt=00, flg=00, set=02)
  instance variables [4]
    addr : integer 2130706433
    port : ""
    hostname : "127.0.0.1"
    socket : nil
}
call stack:
	methoderror:reporterror
		arg this = <instance of primitivefailederror>
	nil:handleerror
		arg this = nil
		arg error = <instance of primitivefailederror>
	thread:handleerror
		arg this = <instance of thread>
		arg error = <instance of primitivefailederror>
	object:throw
		arg this = <instance of primitivefailederror>
	object:primitivefailed
		arg this = <instance of netaddr>
	meta_scnvim:sendjson
		arg this = <instance of meta_scnvim>
		arg object = "{"action":{"help":{"uri":"/u..."
		arg vimport = ""
	meta_scnvim:openhelpfor
		arg this = <instance of meta_scnvim>
		arg text = "sinosc"
		arg vimport = ""
		arg pattern = "/usr/local/bin/pandoc"
		arg pandocpath = nil
		var msg = "{"action":{"help":{"uri":"/u..."
		var uri = <instance of uri>
		var path = "/users/michael/library/appli..."
		var outputpath = "/users/michael/library/appli..."
	process:interpretcmdline
		arg this = <instance of main>
^^ the preceding error dump is for error: primitive '_netaddr_sendraw' failed.
wrong type.
receiver: a netaddr(127.0.0.1, )

**Comment by cdbzb** [comment]
likewise if I enter :SCNvimStatusLine I get

ERROR: Primitive '_NetAddr_SendRaw' failed.
Wrong type.
RECEIVER:
Instance of NetAddr {    (0x10b7abb18, gc=78, fmt=00, flg=00, set=02)
  instance variables [4]
    addr : Integer 2130706433
    port : ""
    hostname : "127.0.0.1"
    socket : nil
}
PROTECTED CALL STACK:
	Meta_MethodError:new	0x11bbb8c00
		arg this = PrimitiveFailedError
		arg what = Wrong type.
		arg receiver = a NetAddr(127.0.0.1, )
	Meta_PrimitiveFailedError:new	0x11bbbf1c0
		arg this = PrimitiveFailedError
		arg receiver = a NetAddr(127.0.0.1, )
	Object:primitiveFailed	0x11cbf3540
		arg this = a NetAddr(127.0.0.1, )
	Meta_SCNvim:sendJSON	0x11e278740
		arg this = SCNvim
		arg object = {"status_line":{"server_status":"0.4% 0.08% 0u 0s","level_meter":"-inf dB"}}
		arg vimPort = nil
	a FunctionDef	0x11d2ac080
		sourceCode = "<an open Function>"
	Routine:prStart	0x11d1cd380
		arg this = a Routine
		arg inval = 614.195927347
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >
		arg error = <instance of PrimitiveFailedError>
	Integer:forBy
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_
		arg this = <instance of Scheduler>
		arg newSeconds = 615.209317306
	Meta_AppClock:tick
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_NetAddr_SendRaw' failed.
Wrong type.
RECEIVER: a NetAddr(127.0.0.1, )

**Comment by cdbzb** [comment]
aaarg - user error - my links to .sc files were broken

...thanks again for this project btw --I would be dead without it!
